### ISSUE TITLE
proposal for extensible and sustainable WIMS docker image 

### ISSUE THREAD

**Issue by jpahullo** [amato-gianluca/docker-wims#15]
Hi @amato-gianluca ,

I am facing the building of a production-ready version of the WIMS docker image, based on your work.

I am having clear which is need for that, at least some requirements right now, to get it extensible and sustainable. Let me explain:

1. Extensible entrypoint.sh
   1. I see that I need to customize what is done inside the entrypoint.sh. The current version is awesome for a local testing.
   2. But for our production infrastructure, I need to customize ssmtp settings, and other things.
   3. So, the idea is to make it possible that anyone, cloning this repo, could customize entrypoint things, without much effort.
   4. This is a win-win: win for this repo, so it is more sustainable and extensible, and win for others that would like to use this repo for having WIMS ready. And probably, would make it possible to receive further contributions.
2. Extensible Dockerfile
   1. Your dockerfile is fantastic.
   2. And I identified the needs to customize apache settings, directories and config files to be aligned on our production environment.
   3. So the idea is to have some bash script, that maybe in this repo may be empty or having a minimal task, so that any one cloning this repo could customize the WIMS image without much effort.

Would you like to receive such a PR?

The idea of this would be to produce the necessary folders and flow to get it done, just producing the same result like the current one. No more no less. But it would let me to extend it easily, cloning this repo, customize the produced WIMS docker image.

What do you think?

Thanks in advance,

Jordi

**Comment by amato-gianluca** [comment]
Sure, go ahead !
