### ISSUE TITLE
proposal of example of a production ready Dockerfile and docker-compose.yml

### ISSUE THREAD

**Issue by jpahullo** [amato-gianluca/docker-wims#16]
Hi @amato-gianluca ,

Would you like me to build a PR with an example of a Dockerfile and docker-compose.yml ready for production?

Having done the other issue #15, maybe it would be a good idea to provide an example of what could be a production-ready WIMS docker image and its docker-compose.yml.

It would be based on what we would put in production. So other can be benefited and other can provide other issues that they may share with this repo.

Let me know.

Thanks a lot for your work,

Jordi

**Comment by amato-gianluca** [comment]
Sure, Jordi, go ahead.

**Comment by jpahullo** [comment]
Thanks @amato-gianluca for accepting this work.

Thanks a lot for your time.

Jordi

**Comment by jpahullo** [comment]
Hi @amato-gianluca ,

I have seen that you added me as co-author on the /Dockerfile. Thanks!!!!

**Comment by amato-gianluca** [comment]
You made really a lot of work !! It was fair to recognize it.
