### ISSUE TITLE
manager_site=list,of,ips but also a range of IPs?

### ISSUE THREAD

**Issue by jpahullo** [amato-gianluca/docker-wims#17]
Hi @amato-gianluca,

I cannot find technial and administration documentation about the config file wims.conf. 

I need to set up an IP range within `manager_site=`. Do yo know how to set an IP range up?

Thanks,

Jordi

**Comment by amato-gianluca** [comment]
I am sure you can specify a partial IP address like 10.0.1. to denote all IP addresses in the subclass 10.0.1.0/24. However, I don't known if a more general subclass notation is allowed.

**Comment by jpahullo** [comment]
Fantastic. That is enough for our use case.

Thanks @amato-gianluca .

Closing it as resolved!
