### ISSUE TITLE
jsme.tgz not available during wims installation

### ISSUE THREAD

**Issue by jpahullo** [amato-gianluca/docker-wims#5]
Hi,

I am building again the institutional image, based on your image.

I amb finding this problem when building the wims image locally using your own Dockerfile solely, when proceeding with the WIMS installation:

```
 => => # --2024-11-04 09:32:32--  (try: 9)  https://wimstest1.di.u-psud.fr/wims/jsme.tgz                                                                                     
 => => # Connecting to wimstest1.di.u-psud.fr (wimstest1.di.u-psud.fr)|129.175.254.10|:443... failed: Connection timed out.                                                  
 => => # Retrying. 
```

This site and file is not available, and building WIMS cannot conclude with success. I am installing the version:

https://sourcesup.renater.fr/frs/download.php/file/6667/wims-4.26.tgz 

Did you notice that?

I record this issue here, meanwhile I will be trying other options, like newer versions.

Thanks for your time,

Jordi

**Comment by jpahullo** [comment]
I tried latest version from wims, but it suffers from the same problem.

I have found that JSME is this https://jsme-editor.github.io/ and I built a patch for compile script to download latest jsme from this URL and not the original.

By now, it is compiling.

If it works, I will push a PR for you to check and accept if necessary. Given that you have contact with WIMS developers, you could contact back them to inform about this.

Thanks,

Jordi

**Comment by jpahullo** [comment]
The image has been built. But I do not know if it works properly with the JSME.

**Comment by Badatos** [comment]
Hi,
As you can see here:
https://wimsedu.info/forums/topic/mise-a-jour-4-28-bug-installation/

This problem can be solved by using this url instead :
wims1.math.cnrs.fr/wims/jsme.tgz


(servers from u-psud.fr are experiencing some issues lately...)

**Comment by jpahullo** [comment]
Thanks @Badatos!

I will apply the patch to compile with the given URL to: https://wims1.math.cnrs.fr/wims/jsme.tgz

**Comment by jpahullo** [comment]
I am regenerating the wims image, to check that all is working again after all single changes.

**Comment by amato-gianluca** [comment]
Thanks for the patch. I will push the image to dockerhub as soon as I can.

**Comment by jpahullo** [comment]
Hi @amato-gianluca,

Thanks for accepting this patch. I created #7 and PR #8 with some other fixes and improvements, if you like to consider.

I will have them into our institution.

Thanks a lot,

Jordi
